/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 lambo.gltf --transform 
Files: lambo.gltf [2.97MB] > lambo-transformed.glb [3.19MB] (-8%)
Author: Jonrss (https://sketchfab.com/huy14320000006)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/lamborghini-venevo-5884f95259ff411c95510cdde5ede33e
Title: Lamborghini venevo
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/lambo-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.PaletteMaterial001} position={[-1.716, 0.502, 0.053]} rotation={[1.578, 0, -0.035]} scale={[-3.366, 3.366, 3.366]} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.material} position={[-1.716, 0.502, 0.053]} rotation={[1.578, 0, -0.035]} scale={[-3.366, 3.366, 3.366]} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.wheel} position={[0.915, 1.325, -4.521]} rotation={[1.578, 0, -0.035]} scale={[-3.653, 3.653, 3.653]} />
      <mesh geometry={nodes.Object_13.geometry} material={materials.material_5} position={[0.915, 1.325, -4.521]} rotation={[1.578, 0, -0.035]} scale={[-3.653, 3.653, 3.653]} />
      <mesh geometry={nodes.Object_15.geometry} material={materials.lamp} position={[-1.716, 0.502, 0.053]} rotation={[1.578, 0, -0.035]} scale={[-3.366, 3.366, 3.366]} />
      <mesh geometry={nodes.Object_16.geometry} material={materials.PaletteMaterial002} position={[-1.716, 0.502, 0.053]} rotation={[1.578, 0, -0.035]} scale={[-3.366, 3.366, 3.366]} />
      <mesh geometry={nodes.Object_17.geometry} material={materials.PaletteMaterial003} position={[-1.716, 0.502, 0.053]} rotation={[1.578, 0, -0.035]} scale={[-3.366, 3.366, 3.366]} />
      <mesh geometry={nodes.Object_19.geometry} material={materials.material_9} position={[-1.716, 0.502, 0.053]} rotation={[1.578, 0, -0.035]} scale={[-3.366, 3.366, 3.366]} />
      <mesh geometry={nodes.Object_23.geometry} material={materials.material_11} position={[-1.716, 0.502, 0.053]} rotation={[1.578, 0, -0.035]} scale={[-3.366, 3.366, 3.366]} />
      <mesh geometry={nodes.Object_27.geometry} material={materials.PaletteMaterial004} position={[-1.716, 0.502, 0.053]} rotation={[1.578, 0, -0.035]} scale={[-3.366, 3.366, 3.366]} />
      <mesh geometry={nodes.Object_33.geometry} material={materials.logo} position={[-1.716, 0.502, 0.053]} rotation={[1.578, 0, -0.035]} scale={[-3.366, 3.366, 3.366]} />
      <mesh geometry={nodes.Object_35.geometry} material={materials.material_17} position={[-1.716, 0.502, 0.053]} rotation={[1.578, 0, -0.035]} scale={[-3.366, 3.366, 3.366]} />
      <mesh geometry={nodes.Object_43.geometry} material={materials.PaletteMaterial005} position={[-1.716, 0.502, 0.053]} rotation={[1.578, 0, -0.035]} scale={[-3.366, 3.366, 3.366]} />
    </group>
  )
}

useGLTF.preload('/lambo-transformed.glb')
